openapi: 3.0.0
info:
  title: Code Runner
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /run_code:
    post:
      summary: Run code
      operationId: runCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
      responses:
        '200':
          description: Code output
  /save_code:
    post:
      summary: Save code
      operationId: saveCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeFile'
      responses:
        '200':
          description: Code saved
components:
  schemas:
    Code:
      type: object
      required:
        - script
        - language
      properties:
        script:
          type: string
          example: "print('Hello, World!')"
        language:
          type: string
          example: "python3"
        input:
          type: string
          example: "50"
        compileOnly:
          type: boolean
          example: false
    CodeFile:
      type: object
      required:
        - filename
        - code
      properties:
        filename:
          type: string
          example: "hello_world.cpp"
        code:
          type: string
          example: "print('Hello, World!')"
